## OS environment parameters
# TensorFlow logging messages. Value 3 is for turning off TensorFlow logging messages
TF_CPP_MIN_LOG_LEVEL: "3"
# For reproducibility
PYTHONHASHSEED: "0"

## Paths and range of years
# The path where the results will be stored
workingPath: 'C:/Users/ThomasChatzopoulos/Documents/project/weak_supervision_enchancement/results'
# workingPath: '/home/ThomasChatzopoulos/projects/weak_supervision_enchancement/results'

# The path where the files, like datasets, are stored.
filesPath: 'C:/Users/ThomasChatzopoulos/Documents/project/weak_supervision_enchancement/files'
# filesPath: '/home/ThomasChatzopoulos/projects/weak_supervision_enchancement/files'


# The first year to consider in the analysis
firstYear: 2006
# The last year to consider in the analysis
lastYear: 2019


## Label functions to use
LFsToUse: [
   "concept_occurrence_label",
   "name_exact",
   "name_exact_lowercase",
   "name_exact_lowercase_no_punc",
   "name_exact_lowercase_tokens",
   "synonyms_exact",
   "synonyms_lowercase",
   "synonyms_lowercase_no_punc",
   "synonyms_lowercase_tokens"
   # "name_exact_negation",
   # "name_exact_lowercase_negation",
   # "name_exact_lowercase_no_punc_negation",
   # "name_exact_lowercase_tokens_no_punc_negation",
   # "synonyms_exact_negation",
   # "synonyms_lowercase_negation",
   # "synonyms_lowercase_no_punc_negation",
   # "synonyms_lowercase_tokens_no_punc_negation"
]

# Store Label Function's probabilities from the Label Model
return_probs: True