## OS environment parameters
# TensorFlow logging messages. Value 3 is for turning off TensorFlow logging messages
TF_CPP_MIN_LOG_LEVEL: "3"
# For reproducibility
PYTHONHASHSEED: "0"

## Paths and range of years
# The path where the results will be stored
workingPath: ### write here the absolute path ###
# The path where the files, like datasets, are stored.
filesPath: ### write here the absolute path ###

# The first year to consider in the analysis
firstYear: 2006
# The last year to consider in the analysis
lastYear: 2019


## Label functions to use
LFsToUse: [
   "concept_occurrence_label",
   "name_exact",
   "name_exact_lowercase",
   "name_exact_lowercase_no_punc",
   "name_exact_lowercase_tokens",
   "synonyms_exact",
   "synonyms_lowercase",
   "synonyms_lowercase_no_punc",
   "synonyms_lowercase_tokens"
   # "name_exact_negation",
   # "name_exact_lowercase_negation",
   # "name_exact_lowercase_no_punc_negation",
   # "name_exact_lowercase_tokens_no_punc_negation",
   # "synonyms_exact_negation",
   # "synonyms_lowercase_negation",
   # "synonyms_lowercase_no_punc_negation",
   # "synonyms_lowercase_tokens_no_punc_negation"
]